const bobotAhp = {
  prospek: 0.227628874,
  kesulitan: 0.046848607,
  nilai_sebelum: 0.112745996,
  minat: 0.612776523,
};

const matrix_wp = {
  cross: [4, 3, 4, 5],
  blockchain: [5, 3, 4, 4],
  cyber_firewall: [4, 3, 4, 4],
  cyber_cloud: [4, 3, 4, 5],
  game3d: [4, 3, 4, 2],
  gamearvr: [4, 3, 4, 2],
  paralel: [4, 4, 4, 0],
  compas: [4, 3, 4, 4],
  multimedia: [3, 3, 4, 3],
};

export const alternatives = [
  {
    id: "cross",
    title: "Cross Mobile",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "oop",
    bobotWP: {
      prospek: 4,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "blockchain",
    title: "Blockchain",
    image: "../images/3dgame.jpg",
    difficulty: 3,
    desc: "Belajar 3D games emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "data_structure",
    bobotWP: {
      prospek: 5,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "cyber_firewall",
    title: "Cyber Firewall",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "computer_security",
    bobotWP: {
      prospek: 4,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "cyber_cloud",
    title: "Cyber Cloud",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "computer_security",
    bobotWP: {
      prospek: 4,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "game3d",
    title: "Game 3D",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "oop",
    bobotWP: {
      prospek: 4,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "gamearvr",
    title: "Game ARVR",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "oop",
    bobotWP: {
      prospek: 4,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "paralel",
    title: "Paralel",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "algoritma",
    bobotWP: {
      prospek: 4,
      kesulitan: 4,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "compas",
    title: "Computer & Society",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "",
    bobotWP: {
      prospek: 4,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
  {
    id: "multimedia",
    title: "Multimedia Concept",
    image: "../images/blockchain.jpg",
    difficulty: 3,
    desc: "Belajar blockchain emang gampang dan mudah sekali, bisa langsung kaya",
    prospect: ["Blockchain developer", "data analyst", "crypto developer"],
    requirement: "",
    bobotWP: {
      prospek: 3,
      kesulitan: 3,
      nilai_sebelum: 0,
      minat: 0,
    },
    ranking: 0,
  },
];
